//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub mod access;
pub mod domain;
pub mod group;
pub mod message;
pub mod prelude;
pub mod role;
pub mod role_access;
pub mod role_domain;
pub mod task;
pub mod user;
pub mod user_group;
pub mod user_role;
