//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::access::Entity as Access;
pub use super::domain::Entity as Domain;
pub use super::group::Entity as Group;
pub use super::message::Entity as Message;
pub use super::role::Entity as Role;
pub use super::role_access::Entity as RoleAccess;
pub use super::role_domain::Entity as RoleDomain;
pub use super::task::Entity as Task;
pub use super::user::Entity as User;
pub use super::user_group::Entity as UserGroup;
pub use super::user_role::Entity as UserRole;
